### ISSUE TITLE
Actualizado Gulp

### ISSUE THREAD

**Issue by CarlosLongarela** [WCGalicia/wordcamp-galicia-2021#4]
Actualicei Gulp para que se execute sen ter que baixar de versión de npm, nas miñas probas funcionou ben, se tedes problemas decideme e miro.

https://github.com/WCGalicia/wordcamp-galicia-2021/tree/carlos

**Comment by danielcharrua** [comment]
@CarlosLongarela lo sigues ejecutando con node v11.15? Yo acabo de probar esta rama con node v15.5 pero no va. 

```
ReferenceError: primordials is not defined
    at fs.js:52:5
    at req_ (/Users/xx/Documents/Web/wordcamp/wordcamp-galicia-2021/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/xx/Documents/Web/wordcamp/wordcamp-galicia-2021/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/xx/Documents/Web/wordcamp/wordcamp-galicia-2021/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
```

**Comment by CarlosLongarela** [comment]
Con Node 14 me ha funcionado sin problemas. Eso sí, si cambias de versión de Node elimina la carpeta `node_modules` y vuelve a ejecutar el `npm install`

**Comment by danielcharrua** [comment]
Perfecto, he cambiado a la version 14 y he instalado nuevamente, todo perfecto ahora. Gracias!
Igual podríamos agregarlo a master, que os parece? @unapersona @CarlosLongarela
